language: minimal
services: docker
env:
  - DOCKER_COMPOSE_VERSION=1.23.2

before install:
  - docker -v && docker-compose -v
 
  
install:
  - docker-compose -f lesson-3-Container/exercises/udacity-c3-deployment/docker/docker-compose-build.yaml build --parallel
